database: &common_database
  host: db.example.net
  port: 3306
  username: leo
  password: dbpassword
  database: my_database
  enabled: true
  legecy: yes

database_new: *common_database

prod_db:
  <<: *common_database
  host: prod-db.example.net
  password: myprodpassword

dev_db:
  <<: *common_database
  host: localhost
  password: password

  